USE [master]
GO

/****** Object:  Database [BlockChain]    Script Date: 11/10/2021 10:39:26 AM ******/
CREATE DATABASE [BlockChain]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BlockChain', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BlockChain.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BlockChain_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BlockChain_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BlockChain].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BlockChain] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BlockChain] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BlockChain] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BlockChain] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BlockChain] SET ARITHABORT OFF 
GO

ALTER DATABASE [BlockChain] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BlockChain] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BlockChain] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BlockChain] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BlockChain] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BlockChain] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BlockChain] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BlockChain] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BlockChain] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BlockChain] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BlockChain] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BlockChain] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BlockChain] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BlockChain] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BlockChain] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BlockChain] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BlockChain] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BlockChain] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BlockChain] SET  MULTI_USER 
GO

ALTER DATABASE [BlockChain] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BlockChain] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BlockChain] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BlockChain] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BlockChain] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BlockChain] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BlockChain] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BlockChain] SET  READ_WRITE 
GO


